# Copyright (c) Prevail Verifier contributors.
# SPDX-License-Identifier: MIT

codecov:
  notify:
    wait_for_ci: yes
    after_n_builds: 2 # (CPP Code Coverage) * (Debug, Release)
comment:
    after_n_builds: 2 # (CPP Code Coverage) * (Debug, Release)
coverage:
  status:
    project:
      default:
        threshold: 0.5%
